### ISSUE TITLE
ex-

### ISSUE THREAD

**Issue by AngelicaMVG** [muktek/assignment--js-object-basics#1]
**ex-01**
- El ultimo assert esta mal numerado.

**ex-04**
- Los últimos asserts tienen mal numerado los obj : esta como nameObj2 y debería ser nameObj3.

**ex-05**
- El indice de moreNamesList[1] === "Ms. Ruby Scooby" debería ser moreNameList[0].

**ex-06**
- El nombre de Jackie esta mal escrito en los asserts, esta como Jacky.

**Comment by muktekguest** [comment]
Thanks, fixed.
